# Project information
site_name: XCash-Labs Docs
site_description: 'XCash-Labs Documentation'
site_author: "XCash-Labs Community"
site_url: 'https://docs.xcashlabs.org'
site_dir: '/var/www/public'

copyright: '© 2026 XCash-Labs Community under <a href="https://opensource.org/licenses/MIT">MIT</a>'

nav:
- Home: 'index.md'
- Interacting:
  - The Basics:
    - Overview: 'interacting/overview.md'
    - Tokenomics: 'technical-specs.md'
    - Networks: 'infrastructure/networks.md'
  - DPOPS Delegate Node:
    - 'interacting/dpops/get-started.md'
  - Download & Verify:
    - Download: 'interacting/download-xcash-binaries.md'
    - Verify: 'interacting/verify-xcash-binaries.md'
  - XCashd:
    - Flags: 'interacting/xcashd-reference.md'
    - Setup Guide:
      - Systemd: 'running-node/monerod-systemd.md'
      - Tor & I2P: 'running-node/monerod-tori2p.md'
    - Sample Configs:
      - Home: 'interacting/xcash-config-file.md'
  - Wallets:
    - xcash-wallet-gui: 'interacting/xcash-wallet-gui-reference.md'
    - xcash-wallet-cli: 'interacting/xcash-wallet-cli-reference.md'
    - xcash-wallet-rpc: 'interacting/xcash-wallet-rpc-reference.md'
    - Advanced Transactions:
      - Multisignature: 'multisignature.md'
      - Offline Transaction Signing: 'cold-storage/offline-transaction-signing.md'
  - Voting and Staking:
    - 'interacting/staking/index.md'
  - Blockchain Tools:
    - xcash-blockchain-export: 'interacting/xcash-blockchain-export-reference.md'
    - xcash-blockchain-import: 'interacting/xcash-blockchain-import-reference.md'
  - External:
    - XCashPulse: 'infrastructure/xcash-pulse.md'
- RPC Library:
  - Node RPC: 'rpc-library/xcashd-rpc.md'
  - Wallet RPC: 'rpc-library/wallet-rpc.md'
- R&D:
  - 'development/index.md'
  - Address Types:
    - 'public-address/index.md'
    - Standard: 'public-address/standard-address.md'
    - Subaddress: 'public-address/subaddress.md'
    - Integrated: 'public-address/integrated-address.md'
  - Cryptography:
    - 'cryptography/index.md'
    - Asymmetric: # Needs clarity
      - Introduction: 'cryptography/asymmetric/introduction.md'
      - Private keys: 'cryptography/asymmetric/private-key.md'
      - Public keys: 'cryptography/asymmetric/public-key.md'
      - Edwards25519 curve: 'cryptography/asymmetric/edwards25519.md'
      - Key image: 'cryptography/asymmetric/key-image.md'
    - Base58: 'cryptography/base58.md'
    - Keccak-256: 'cryptography/keccak-256.md'
    - PRNG: 'cryptography/prng.md'
  - Mnemonics:
    - 'mnemonics/index.md'
    - Legacy: 'mnemonics/legacy.md'
    - MyMonero: 'mnemonics/mymonero.md'
    - Polyseed: 'mnemonics/polyseed.md'
  - Delegated Proof of Private Stake:
    - 'proof-of-work/index.md'
    - PoW in Cryptocurrencies: 'proof-of-work/pow-in-cryptocurrencies.md'
    - CryptoNight: 'proof-of-work/cryptonight.md'
    - RandomX: 'proof-of-work/random-x.md'

theme:
  name: material
  custom_dir: overrides
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.path
    # - navigation.prune
    # - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  favicon: images/favicon.ico
  icon:
    logo: logo
  logo: 'images/xcash.svg'
  static_templates:
    - 404.html

extra_css:
  - overrides.css

extra:
  social:
    - icon: material/web
      link: https://docs.xcashlabs.org
      name: Clearnet Website
    - icon: fontawesome/brands/github
      link: https://github.com/Xcash-Labs/xcashlabs-docs
      name: GitHub Repository

repo_name: 'Xcash-Labs/xcashlabs-docs'
repo_url: 'https://github.com/Xcash-Labs/xcashlabs-docs'
# todo: change to master branch
edit_uri: blob/master/docs/

markdown_extensions:
  # https://squidfunk.github.io/mkdocs-material/extensions/admonition/
  - admonition
  - abbr
  - def_list
  - attr_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.details
  - pymdownx.highlight:
      use_pygments: true         # build time highlighting, not client side
  - pymdownx.inlinehilite
  - pymdownx.superfences         # nest code blocks inside codeblocks
  - pymdownx.snippets            # insert content from other files
  - pymdownx.tabbed:
      alternate_style: true
  - tables

plugins:
  - search
  - minify:
      minify_html: true
      minify_js: true
      htmlmin_opts:
        remove_comments: true
  - privacy
  - macros:
      include_dir: docs/macros/includes
      include_yaml:
        - docs/macros/monerod.yml
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: fr
          name: Français
          build: false
        - locale: es
          name: Español
          build: false
        - locale: it
          name: Italiano
          build: false
        - locale: pl
          name: Polski
          build: false
        - locale: ar
          name: العربية
          build: false
        - locale: ru
          name: Русский
          build: false
        - locale: de
          name: Deutsch
          build: false
        - locale: nl
          name: Nederlands
          build: false
        - locale: pt
          name: Português
          build: false
        - locale: tr
          name: Türkçe
          build: false
        - locale: zh
          name: 中文 (简体)
          build: false
        - locale: zh-TW
          name: 中文 (繁體)
          build: false
        - locale: nb
          name: Norsk Bokmål
          build: false
